using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Client.Eui;
using Content.Client._Maid.UserInterface.Chart;
using Content.Shared._Maid.AdaptiveGameMode;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Console;
using Robust.Shared.IoC;
using Robust.Shared.Maths;

namespace Content.Client._Maid.AdaptiveGameMode;

[GenerateTypedNameReferences]
public sealed partial class AdaptiveStatsWindow : DefaultWindow
{
    [Dependency] private readonly IClientConsoleHost _console = default!;

    private readonly AdaptiveStatsEui _eui;

    private AdaptiveStatsEuiState? _lastState;
    private int? _selectedRoundId;
    private int? _selectedRunId;

    public AdaptiveStatsWindow(AdaptiveStatsEui eui)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _eui = eui;

        RoundSelect.OnItemSelected += OnRoundSelected;
        ToggleTracking.OnToggled += OnTrackingToggled;
        CalculateButton.OnPressed += OnCalculatePressed;
        Chart.OnPointClicked += OnPointClicked;
        Chart.OnPointHovered += OnPointHovered;
    }

    private void OnRoundSelected(OptionButton.ItemSelectedEventArgs args)
    {
        _selectedRoundId = (int?)RoundSelect.GetItemMetadata(args.Id);
        _selectedRunId = null;
        UpdateUI();
    }

    private void OnTrackingToggled(BaseButton.ButtonToggledEventArgs args)
    {
        _eui.SendToggleMessage(args.Pressed);
    }

    private void OnCalculatePressed(BaseButton.ButtonEventArgs args)
    {
        _eui.SendCalculateMessage();
    }

    private void OnPointClicked(float x)
    {
        var run = FindRunByX(x);
        if (run == null)
            return;

        _selectedRunId = run.Id;
        UpdateTable();
    }

    private void OnPointHovered(float? x)
    {
        if (x == null)
        {
            if (_selectedRunId != null)
            {
                TableTitle.Text = $"Run {_selectedRunId.Value} details:";
                PopulateTableForRun(_selectedRunId.Value);
            }
            else
            {
                TableTitle.Text = "No calculation run selected. Hover/click points in the chart.";
                TableGrid.DisposeAllChildren();
            }
            return;
        }

        var run = FindRunByX(x.Value);
        if (run == null)
            return;

        TableTitle.Text = $@"Hovering Run {run.Id} details (Time: {run.Time:hh\:mm\:ss}):";
        PopulateTableForRun(run.Id);
    }

    private SharedAdaptiveCalculationRun? FindRunByX(float x)
    {
        if (_lastState == null || _selectedRoundId == null)
            return null;

        var runs = _lastState.RoundData.GetValueOrDefault(_selectedRoundId.Value);
        if (runs == null || runs.Count == 0)
            return null;

        SharedAdaptiveCalculationRun? closestRun = null;
        var closestDistance = float.MaxValue;
        foreach (var run in runs)
        {
            var runX = (float)run.Time.TotalMinutes;
            var dist = MathF.Abs(x - runX);
            if (dist < closestDistance)
            {
                closestDistance = dist;
                closestRun = run;
            }
        }

        return closestRun;
    }

    public void UpdateState(AdaptiveStatsEuiState state)
    {
        _lastState = state;

        ToggleTracking.Pressed = state.TrackingEnabled;

        var selectedId = _selectedRoundId ?? state.CurrentRoundId;
        RoundSelect.Clear();
        var indexToSelect = 0;
        var i = 0;
        foreach (var roundId in state.RoundData.Keys)
        {
            RoundSelect.AddItem($"Round {roundId}");
            RoundSelect.SetItemMetadata(i, roundId);
            if (roundId == selectedId)
            {
                indexToSelect = i;
            }
            i++;
        }

        if (state.RoundData.Count > 0 && !state.RoundData.ContainsKey(selectedId))
        {
            selectedId = state.CurrentRoundId;
            i = 0;
            foreach (var roundId in state.RoundData.Keys)
            {
                if (roundId == selectedId)
                {
                    indexToSelect = i;
                    break;
                }
                i++;
            }
        }

        if (state.RoundData.Count > 0)
        {
            RoundSelect.SelectId(indexToSelect);
            _selectedRoundId = selectedId;
        }

        UpdateUI();
    }

    private void UpdateUI()
    {
        if (_lastState == null || _selectedRoundId == null)
            return;

        var runs = _lastState.RoundData.GetValueOrDefault(_selectedRoundId.Value) ?? new List<SharedAdaptiveCalculationRun>();

        if (runs.Count > 0)
        {
            var latest = runs[^1];
            InfoLabel.Text = $"Round ID: {_selectedRoundId.Value} | Calculations: {runs.Count} | Latest score: Chaos={latest.TotalChaos}, Combat={latest.TotalCombat} (Target Chaos={latest.TargetChaos}, Target Combat={latest.TargetCombat})";
        }
        else
        {
            InfoLabel.Text = $"Round ID: {_selectedRoundId.Value} | No statistics recorded.";
        }

        Chart.ClearSubRenderers();

        var chaosPoints = new List<Vector2>();
        var combatPoints = new List<Vector2>();
        var targetChaosPoints = new List<Vector2>();
        var targetCombatPoints = new List<Vector2>();

        var maxVal = 10f;
        var maxX = 10f;
        foreach (var run in runs)
        {
            var xVal = (float)run.Time.TotalMinutes;
            chaosPoints.Add(new Vector2(xVal, run.TotalChaos));
            combatPoints.Add(new Vector2(xVal, run.TotalCombat));
            targetChaosPoints.Add(new Vector2(xVal, run.TargetChaos));
            targetCombatPoints.Add(new Vector2(xVal, run.TargetCombat));

            if (xVal > maxX)
                maxX = xVal;

            // LOL they don't have params[] overload
            maxVal = MathF.Max(MathHelper.Max(run.TotalChaos, run.TotalCombat, run.TargetChaos, run.TargetCombat), maxVal);
        }

        var spacingX = Math.Max(1f, MathF.Ceiling(maxX / 10f));
        var spacingY = Math.Max(5f, MathF.Ceiling(maxVal / 10f));

        Chart.AddSubRenderer(new BackgroundGridRenderer(spacingX, spacingY, Color.FromHex("#222222")));
        Chart.AddSubRenderer(new ChartAxesRenderer(spacingX, spacingY, Color.White, 8));
        Chart.AddSubRenderer(new ConnectedChartRenderer(chaosPoints, Color.Red, "Chaos"));
        Chart.AddSubRenderer(new ConnectedChartRenderer(combatPoints, Color.Blue, "Combat"));
        Chart.AddSubRenderer(new ConnectedChartRenderer(targetChaosPoints, Color.FromHex("#8b2525"), "Target Chaos"));
        Chart.AddSubRenderer(new ConnectedChartRenderer(targetCombatPoints, Color.FromHex("#25258b"), "Target Combat"));

        Chart.AutoFit();
        if (_selectedRunId != null)
        {
            var exists = runs.Any(run => run.Id == _selectedRunId.Value);

            if (!exists)
                _selectedRunId = null;
        }

        if (_selectedRunId == null && runs.Count > 0)
        {
            _selectedRunId = runs[^1].Id;
        }

        UpdateTable();
    }

    private void UpdateTable()
    {
        if (_selectedRunId == null)
        {
            TableTitle.Text = "No calculation run selected. Hover/click points in the chart.";
            TableGrid.DisposeAllChildren();
            return;
        }

        TableTitle.Text = $"Run {_selectedRunId.Value} details:";
        PopulateTableForRun(_selectedRunId.Value);
    }

    private void PopulateTableForRun(int runId)
    {
        TableGrid.DisposeAllChildren();

        if (_lastState == null || _selectedRoundId == null)
            return;

        var runs = _lastState.RoundData.GetValueOrDefault(_selectedRoundId.Value);
        if (runs == null)
            return;

        var selectedRun = runs.FirstOrDefault(run => run.Id == runId);

        if (selectedRun == null)
            return;

        TableGrid.AddChild(new Label { Text = "Name", StyleClasses = { "Bold" } });
        TableGrid.AddChild(new Label { Text = "Entity UID", StyleClasses = { "Bold" } });
        TableGrid.AddChild(new Label { Text = "Prototype ID", StyleClasses = { "Bold" } });
        TableGrid.AddChild(new Label { Text = "Chaos", StyleClasses = { "Bold" } });
        TableGrid.AddChild(new Label { Text = "Combat", StyleClasses = { "Bold" } });
        TableGrid.AddChild(new Label { Text = "Actions", StyleClasses = { "Bold" } });

        foreach (var record in selectedRun.Records)
        {
            TableGrid.AddChild(new Label { Text = record.Name });
            TableGrid.AddChild(new Label { Text = record.Entity.ToString() });
            TableGrid.AddChild(new Label { Text = record.Prototype ?? "N/A" });
            TableGrid.AddChild(new Label { Text = record.Chaos.ToString("0.##") });
            TableGrid.AddChild(new Label { Text = record.Combat.ToString("0.##") });

            var viewButton = new Button { Text = "View" };
            viewButton.OnPressed += _ =>
            {
                _console.ExecuteCommand($"follow {record.Entity}");
            };
            TableGrid.AddChild(viewButton);
        }
    }
}
